### ISSUE TITLE
Double scan and reloading app

### ISSUE THREAD

**Issue by sergeykotor** [darryncampbell/react-native-datawedge-intents#13]
**Hello!** 
In the debug mode, when scanning the date matrix codes, it is reloaded. There is also the problem of double scanning, when the scanner does not go into disabled mode immediately, but only after the second scan. And if it turns out to be scanned once, then two entries are displayed in the console. React version 0.63, device TC70

**Comment by sergeykotor** [comment]
https://user-images.githubusercontent.com/53668790/104464720-4edd2980-55c4-11eb-9f4c-7a6555e692e3.mp4

**Comment by sergeykotor** [comment]
**Source**

`import React, {Component} from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import DataWedgeIntents from 'react-native-datawedge-intents';
import {DeviceEventEmitter} from 'react-native';

export default class RNDataWedgeIntentDemo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      enumeratedScanners: 'Scanners will appear here',
      barcodeLabelType: '',
      barcodeData: '',
      barcodeSource: '',
    };
    this.scanHandler = (deviceEvent) => {
       DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SOFTSCANTRIGGER,
                    DataWedgeIntents.STOP_SCANNING,
                  );
      console.log('LOGS'+JSON.stringify(deviceEvent));
      this.state.barcodeData = deviceEvent.data;
      this.state.barcodeLabelType = deviceEvent.labelType;
      this.state.barcodeSource = deviceEvent.source;
      this.setState(this.state);
    };
    this.enumerateScannersHandler = (deviceEvent) => {
      //console.log(deviceEvent);
      let scanners = '';
      for (let i = 0; i < deviceEvent.Scanners.length; i++) {
        scanners = scanners + '[' + deviceEvent.Scanners[i] + '] ';
      }
      this.state.enumeratedScanners = scanners;
      this.setState(this.state);
    };
    DeviceEventEmitter.addListener(
      'enumerated_scanners',
      this.enumerateScannersHandler,
    );
    DeviceEventEmitter.addListener('barcode_scan', this.scanHandler);
    //  NOTE: DataWedge must be configured to send intents with this action for the demo to work (do not specify a category)
    //  Feel free to modify this call to listen for a different action.
    DataWedgeIntents.registerReceiver('com.zebra.scantest.ACTION', '');
  }

  render() {
    let barcodeData = this.state.barcodeData;
    let barcodeType = this.state.barcodeLabelType;
    let barcodeSource = this.state.barcodeSource;
    let enumeratedScanners = this.state.enumeratedScanners;
    return (
      <ScrollView>
        <View style={styles.container}>
          <View style={styles.row}>
            <Text style={styles.rowText}>
              Scanned Data: {barcodeData} - {barcodeType}
            </Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Soft Scan Trigger:</Text>
            <View style={styles.optionsView}>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SOFTSCANTRIGGER,
                    DataWedgeIntents.START_SCANNING,
                  );
                }}>
                <Text style={styles.optionsText}>START_SCANNING</Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SOFTSCANTRIGGER,
                    DataWedgeIntents.STOP_SCANNING,
                  );
                }}>
                <Text style={styles.optionsText}>STOP_SCANNING</Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SOFTSCANTRIGGER,
                    DataWedgeIntents.TOGGLE_SCANNING,
                  );
                }}>
                <Text style={styles.optionsText}>TOGGLE_SCANNING</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Scanner Input Plugin:</Text>
            <View style={styles.optionsView}>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SCANNERINPUTPLUGIN,
                    DataWedgeIntents.ENABLE_PLUGIN,
                  );
                }}>
                <Text style={styles.optionsText}>ENABLE_SCANNING</Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SCANNERINPUTPLUGIN,
                    DataWedgeIntents.DISABLE_PLUGIN,
                  );
                }}>
                <Text style={styles.optionsText}>DISABLE_SCANNING</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Enumerate Scanners:</Text>
            <View style={styles.optionsView}>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_ENUMERATESCANNERS,
                  );
                }}>
                <Text style={styles.optionsText}>ENUMERATE</Text>
              </TouchableOpacity>
              <Text style={styles.optionsTextNoColor}>
                {enumeratedScanners}
              </Text>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Set Default Profile:</Text>
            <View style={styles.optionsView}>
              <TextInput
                style={{width: 250}}
                placeholder="Profile Name"
                onChangeText={(profileText) => this.setState({profileText})}
              />
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SETDEFAULTPROFILE,
                    this.state.profileText,
                  );
                }}>
                <Text style={styles.optionsText}>SET DEFAULT PROFILE</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Reset Default Profile:</Text>
            <View style={styles.optionsView}>
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_RESETDEFAULTPROFILE,
                  );
                }}>
                <Text style={styles.optionsText}>RESET DEFAULT PROFILE</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.row}>
            <Text style={styles.rowText}>Switch to Profile:</Text>
            <View style={styles.optionsView}>
              <TextInput
                style={{width: 250}}
                placeholder="Profile Name"
                onChangeText={(switchText) => this.setState({switchText})}
              />
              <TouchableOpacity
                onPress={() => {
                  DataWedgeIntents.sendIntent(
                    DataWedgeIntents.ACTION_SWITCHTOPROFILE,
                    this.state.switchText,
                  );
                }}>
                <Text style={styles.optionsText}>SWITCH TO PROFILE</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: '#F5FCFF',
  },
  optionsView: {
    alignItems: 'flex-start',
    flexDirection: 'column',
    margin: 5,
  },
  rowText: {
    fontSize: 18,
    textAlign: 'left',
    color: '#555555',
    margin: 2,
  },
  optionsText: {
    fontSize: 14,
    textAlign: 'center',
    color: '#ffffff',
    backgroundColor: '#0077a0',
    padding: 10,
    margin: 1,
  },
  optionsTextNoColor: {
    fontSize: 14,
    textAlign: 'center',
    padding: 10,
    margin: 1,
  },
  row: {
    margin: 5,
    flexDirection: 'column',
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
`

**Comment by sergeykotor** [comment]
https://snack.expo.io/@sergeykotor/8f9ff2 source, but i dont use expo, just for show

**Comment by darryncampbell** [comment]
Thanks for sharing, I have a few questions / points:

- I see you are using a modified version of https://github.com/darryncampbell/RNDataWedgeIntentDemo, does an unmodified version of this application display the same behaviour?  
- I have not looked at https://github.com/darryncampbell/RNDataWedgeIntentDemo in over 3 years so I would recommend using https://github.com/darryncampbell/DataWedgeReactNative which is a more recent application - it is at least a known-working example.
- I took a look at the source you shared above but I do not see anything obviously wrong with the code so I am unsure at this point what the root cause of the issue could be.

**Comment by sergeykotor** [comment]
Thanks for answer!
1. I cant install this project.
2. Attached a video of the behavior of this
![photo_2021-01-14_09-59-35](https://user-images.githubusercontent.com/53668790/104555644-43831000-564f-11eb-9738-02401d7adb07.jpg)
![photo_2021-01-14_09-59-51](https://user-images.githubusercontent.com/53668790/104555645-441ba680-564f-11eb-99f6-d843967d2ec8.jpg)
![photo_2021-01-14_09-59-15](https://user-images.githubusercontent.com/53668790/104555648-44b43d00-564f-11eb-84f7-316c1e21dfd7.jpg)



https://user-images.githubusercontent.com/53668790/104555412-dec7b580-564e-11eb-93eb-6b94ab043422.MOV

**Comment by sergeykotor** [comment]
@darryncampbell 
I built your application and now it seems to work correctly

https://user-images.githubusercontent.com/53668790/104565365-3e2cc200-565d-11eb-9acc-f8e6f305c258.mp4

**Comment by darryncampbell** [comment]
That is so strange.  Could it be that you are running in debug and something to do with hot reload causing multiple broadcast receivers (or observers?) to be registered without unregistering the previous ones, that would explain why you are getting inconsistent behaviour and the multiple scans, though would not explain the app reloading behaviour.

I see a `genericReceiver` object that is not unregistered in the `onHostPause()` method, that could be the root cause. I also see a comment at https://github.com/darryncampbell/react-native-datawedge-intents/blob/master/android/src/main/java/com/darryncampbell/rndatawedgeintents/RNDataWedgeIntentsModule.java#L100 saying this is expected behaviour... it has been a long time since I looked at this code but it looks as though there was some discussion on how it should work when I first implemented it - that could be the root cause of what you are seeing but if I'm right, and this is related to hot reload, this would only be seen during development.

**Comment by sergeykotor** [comment]
@darryncampbell 
Thanks for the answer! Maybe this is really hot reload. And I noticed another bug 
in the  builded version, after several scans (10-15) new barcodes are not added to the beginning of the list. 

https://user-images.githubusercontent.com/53668790/104689056-e94b8300-5712-11eb-9919-d20f69425178.MOV

**Comment by darryncampbell** [comment]
> in the builded version, after several scans (10-15) new barcodes are not added to the beginning of the list.

That would definitely be some problem with my app rather than the Intent plugin - I add the scan to the array at https://github.com/darryncampbell/DataWedgeReactNative/blob/master/App.js#L259, I guess there is something wrong with that logic

**Comment by sergeykotor** [comment]
@darryncampbell 
Please, sorry about offtop! Сan android 5.1 with gms be installed for my tc70 TC700H-KC11ES-IN android 4.4 without gms?

**Comment by darryncampbell** [comment]
@sergeykotor Yes, you can (the link to the download is https://www.zebra.com/us/en/support-downloads/software/operating-system/tc70-operating-system.html) but you need to have a support contract or some other eligibility to download the image.  If you don't have those then there is a 'contact support' button in the top right hand corner.

Once you have access to the download, follow the instructions in the ReadMe and be aware of step 5g:
```
Next step only if you are switching between GMS and NON-GMS software, otherwise this
step is not required.
• If you are updating device from GMS to NON-GMS or Vice Versa, it is required to
either use T70N0LXXARFXX21002.zip (Factory Reset Package v02.10.02) (Factory
Reset, this will give complete OOB experience) or at Minimum, please do a
T70N0LXXAREXX21002.zip (Enterprise Reset Package v02.10.02)
```

**Comment by sergeykotor** [comment]
![image](https://user-images.githubusercontent.com/53668790/105042518-66f5f280-5a75-11eb-9123-c75f1838761c.png)
I need these files? Because i can download without support contract now.

**Comment by darryncampbell** [comment]
Yes, that is right.  Install the Full Software Update, Factory Reset, then the Mandatory Patch, then the latest Lifeguard release (17).  Instructions should be in the readme but in short:
- adb reboot recovery
- adb sideload <package zip>
- Repeat the above steps for the remaining 3 packages

Note, all data on the device will be lost when you Factory Reset!!!

**Comment by sergeykotor** [comment]
@darryncampbell 
Thank you! I am grateful for your advice.

**Comment by sergeykotor** [comment]
I updated android, installed liveguard update, and now all problems (with debugging, double scanning, etc.) are gone. 
Thank you again

**Comment by sergeykotor** [comment]
The problem with multiple scans is still present, it appears if you make code edits in the debug.

**Comment by darryncampbell** [comment]
There is a bug in the sample app, you will need to unregister / reregister the event emitter during a reload, like this:

```
  componentDidMount()
  {
    this.state.deviceEmitterSubscription = DeviceEventEmitter.addListener('datawedge_broadcast_intent', (intent) => {this.broadcastReceiver(intent)});
    this.registerBroadcastReceiver();
    this.determineVersion();
  }

  componentWillUnmount()
  {
    this.state.deviceEmitterSubscription.remove();
  }
```

**Comment by darryncampbell** [comment]
https://github.com/darryncampbell/DataWedgeReactNative/commit/79d5325f486bae3c4cd7c45486f7ded189ca5a9c

**Comment by sergeykotor** [comment]
@darryncampbell 
I've done this before, and it didn't help

**Comment by sergeykotor** [comment]
@darryncampbell 
I downloaded the project from the git again and now the logs are working normally, but at start is sends a signal that a scan has occurred.
Some kind of intent not related to the scanner comes
https://github.com/darryncampbell/DataWedgeReactNative/blob/a915464dff023b7b276e9fee3354618e7e3521ef/App.js#L140
![image](https://user-images.githubusercontent.com/53668790/105495667-7e2f1d00-5ccd-11eb-8575-d797daf88f90.png)

**Comment by sergeykotor** [comment]
Maybe some kind of intent not related to the scanner comes?
https://github.com/darryncampbell/DataWedgeReactNative/blob/a915464dff023b7b276e9fee3354618e7e3521ef/App.js#L140

**Comment by darryncampbell** [comment]
Strange, I could not reproduce that "Scan: undefined" message - do you just launch the app and then see it or are there other reproduction steps?

**Comment by sergeykotor** [comment]
I launched the application after a few days and the error disappeared. Maybe it was my problem.
