### ISSUE TITLE
Problem after focusing TextInput

### ISSUE THREAD

**Issue by sergeykotor** [darryncampbell/react-native-datawedge-intents#16]
Hello! If I scan without working with the textinput before that, everything happens fine, but if I worked with the textinput before scanning, then the scanned text is filled into the textinput that was last in focus. Can it be fixed?

**Comment by darryncampbell** [comment]
Please disable keyboard output in your DataWedge plugin for this app. Open the DataWedge app, select profile then scroll down until you see keyboard output plugin

**Comment by sergeykotor** [comment]
@darryncampbell Thank you very much! Helped again!
