### ISSUE TITLE
How to enable 'code interleaved2of5' type using PARAM_LIST{ } by default? 

### ISSUE THREAD

**Issue by aithashi** [darryncampbell/react-native-datawedge-intents#20]
It would be really helpful to know how to enable one of the types (**'code interleaved2of5'**) in the created profile.
I'm aware we can do this like follow:
`            "PARAM_LIST": {
                //"current-device-id": this.selectedScannerId,
                "scanner_selection": "auto",
                "decoder_ean8": "" + this.state.ean8checked,
                "decoder_ean13": "" + this.state.ean13checked,
                "decoder_code128": "" + this.state.code128checked,
                "decoder_code39": "" + this.state.code39checked
            }`
            
            But not sure what's the key here for the type **'interleaved 2of5'**
            
            Thanks in advance __/\__

**Comment by darryncampbell** [comment]
Hi, It should be `decoder_i2of5`, https://techdocs.zebra.com/datawedge/latest/guide/api/setconfig/#scannerinputparameters

**Comment by aithashi** [comment]
@darryncampbell  Thank you so much. It works in dev mode.

But i'm not sure how to handle profile in release mode.
One of the examples code here has 2 profiles. Not sure why and how?

(I will paste my code here if I find this working in release mode)
Thanks again

**Comment by darryncampbell** [comment]
Hi @aithashi , the debug and release versions of your app should behave identically wrt DataWedge profiles unless you have specific logic in your app that is different.

**Comment by aithashi** [comment]
@darryncampbell 
	Thank you so much again. It worked
and following is my profile code
`		var profileConfig = {
			"PROFILE_NAME": "MyApp",
			"PROFILE_ENABLED": "true",
			"CONFIG_MODE": "UPDATE",
			"PLUGIN_CONFIG": {
				"PLUGIN_NAME": "BARCODE",
				// "RESET_CONFIG": "true",
				"PARAM_LIST": {
					"scanner_selection": "auto",
					"decoder_code128": "" + true,
					"decoder_code39": "" + true,
					"decoder_i2of5": "" + true,
				}
			},
			"APP_LIST": [{
				"PACKAGE_NAME": "com.myapp",
				"ACTIVITY_LIST": ["*"]
			}]
		};`
		

`		var profileConfig2 = {
			"PROFILE_NAME": "MyApp",
			"PROFILE_ENABLED": "true",
			"CONFIG_MODE": "UPDATE",
			"PLUGIN_CONFIG": {
				"PLUGIN_NAME": "INTENT",
				"RESET_CONFIG": "true",
				"PARAM_LIST": {
					"intent_output_enabled": "true",
					"intent_action": "com.zebra.reactnativedemo.ACTION",
					"intent_delivery": "2",
					"decoder_code128": "" + true,
					"decoder_code39": "" + true,
					"decoder_i2of5": "" + true,
				}
			}
		};`
		I have commented // "RESET_CONFIG": "true", (Not sure why, But this above combinational worked fine)

**Comment by darryncampbell** [comment]
For what you are doing, I think the RESET_CONFIG variable will not matter, though if unspecified it will default to 'true' anyway
