### ISSUE TITLE
intents send from cmd  are not received 

### ISSUE THREAD

**Issue by mrojas18** [darryncampbell/react-native-datawedge-intents#24]
hi!! great work! 

sorry for my english, 

i'm having this issue, 

currently i'm developing an app, and right now i have a device TC-21, and everything works good, but when i try to send an intent with some data from cmd, the intent is send, but on the app is not received, 

example of intent 
adb shell am start -a com.famiq.logistica.SCAN -c android.intent.category.DEFAULT -e com.symbol.datawedge.data_string 2021038932 -e com.symbol.datawedge.source scanner -e com.symbol.datawedge.label_type LABEL-TYPE-EAN13

config profile 

var profileConfig = {
        "PROFILE_NAME": "FamiqLogisticaApp",
        "PROFILE_ENABLED": "true",
        "CONFIG_MODE": "UPDATE",
        "PLUGIN_CONFIG": {
            "PLUGIN_NAME": "BARCODE",
            "RESET_CONFIG": "true",
            "PARAM_LIST": {}
        },
        "APP_LIST": [{
            "PACKAGE_NAME": "com.famiq.logistica",
            "ACTIVITY_LIST": ["*"]
        }]
    };

can you help me?

**Comment by mrojas18** [comment]
sorry i'm going to close the issue, 
i have found that on the class RNDataWedgeIntentsModule the method genericReceiver just add the extra v2API, without that it never pass throght the datawedgeintentsmodule, 

public static BroadcastReceiver genericReceiver = new BroadcastReceiver()
    {
        @Override
        public void onReceive(Context context, Intent intent) {
            Log.v(TAG, "Received Broadcast from DataWedge");
            intent.putExtra("v2API", true);
            ObservableObject.getInstance().updateValue(intent);
        }
    };


i just add that extra on my intent on the cmd 

adb shell am start -a com.famiq.logistica.SCAN -c android.intent.category.DEFAULT -e com.symbol.datawedge.data_string 2021038932 -e com.symbol.datawedge.source scanner -e com.symbol.datawedge.label_type LABEL-TYPE-EAN13 -e v2API true

**Comment by darryncampbell** [comment]
Hi, is this still an open issue?  I see it was closed and reopened.
**If this is still an issue, could you please provide the configuration of your DtaaWedge output plugin(s)?**
Also, I assume you have seen it but if not, this article will be relevant: https://developer.zebra.com/community/home/blog/2018/12/20/testing-your-zebra-scanning-application-on-an-emulator

**Comment by mrojas18** [comment]
hi!! thanks for your answer, 

it looks like i should change start by broadcast on the intent, 


adb shell am **broadcast** -a com.famiq.logistica.SCAN -c android.intent.category.DEFAULT -e com.symbol.datawedge.data_string 2021038932 -e com.symbol.datawedge.source scanner -e com.symbol.datawedge.label_type LABEL-TYPE-EAN13

thanks!!
