### ISSUE TITLE
error with react-native 0.55

### ISSUE THREAD

**Issue by FrancescaBarbazeni** [darryncampbell/react-native-datawedge-intents#3]
Hi Darry,

with the new react-native this module give me an error

undefined is not an object (evaluating 'RNDataWedgeIntents.ACTION_SOFTSCANTRIGGER')
have you any idea of the problem?
Thank you

"react": "^16.3.14",
"react-native": "^0.55.13"

**Comment by darryncampbell** [comment]
Hi, I am not sure what could be going on... I have not updated or looked at this project in quite some time but hopefully I will find some time next week to take a look.

**Comment by FrancescaBarbazeni** [comment]
thank you so much!

**Comment by FrancescaBarbazeni** [comment]
After some troubles now I'm able to make it works. Thank you so much for your reply. It shoud be amazing if it could be possible to use this module with create-react-native-app; I'm force to eject from the build because I'm forced to use the command `react-native link` in order to install it.

Could it be possibile to solve this problem in your opinion?
I don't know how to fix it, anyway I can try to give you some help working together.

Thank you again
bye

**Comment by darryncampbell** [comment]
Hi, I don't think it is possible to have this plugin work with create-react-native-app.  Looking at https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html under "What about native code?" it says if you need native functionality (this this plugin provides) then you need to use react-native link, as you have done.

**Comment by FrancescaBarbazeni** [comment]
ok thank you so much!

**Comment by mindaugasnakrosis** [comment]
@FrancescaBarbazeni How are you launching you app in terminal in development environment? Are you still using expo? I am having a similar problem: https://github.com/darryncampbell/react-native-datawedge-intents/issues/14
